export const skillsData = [
    {
        label:"FRONT END",
         data:[
            {
                skillName:"HTML",
                percentage:"90",
            },
            {
                skillName:"CSS",
                percentage:"50",
            },
            {
                skillName:"JAVASCRIPT",
                percentage:"80",
            },
            {
                skillName:"React.JS",
                percentage:"70",
            }
         ]
    },

    {
        label:"FRONT END",
         data:[
            {
                skillName:"HTML",
                percentage:"90",
            },
            {
                skillName:"CSS",
                percentage:"50",
            },
            {
                skillName:"JAVASCRIPT",
                percentage:"80",
            },
            {
                skillName:"React.JS",
                percentage:"70",
            }
         ]
    },
    {
        label:"FRONT END",
         data:[
            {
                skillName:"HTML",
                percentage:"90",
            },
            {
                skillName:"CSS",
                percentage:"50",
            },
            {
                skillName:"JAVASCRIPT",
                percentage:"80",
            },
            {
                skillName:"React.JS",
                percentage:"70",
            }
         ]
    }
]